project:
  type: website
  output-dir: docs

website:
  title: "R-Volution Takimi "
  navbar:
    search: true
    left:
      - text: Ana Sayfa
        href: index.qmd
      - text: Takim uyeleri
        href: takim.qmd
      - text: Porfolyo
        href: portfolyo.qmd
      - text: Proje
        href: proje.qmd


            
    tools:
      - icon: github
        href: https://github.com

  sidebar:
    - title: "Calismalari"
      style: "docked"
      search: true
      contents:
        - portfolyo.qmd
        - portfolyo/calisma1.qmd
        - portfolyo/calisma2.qmd  
        
    - title: "Takim"
      style: "docked"
      search: true
      contents:
        - takim.qmd
        - takim/ahmetcanbisit.qmd
        - takim/kaanguven.qmd
        - takim/melihozen.qmd  
        - takim/yigitboran.qmd  
        - takim/leventbekci.qmd  
        
        
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "EMU Hacettepe MUY665 - 2023-2024 Bahar" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: simplex 
      dark: cyborg
    css: styles.css


editor: visual


